name: 下载JM本子 (dispatch)

on:
  workflow_dispatch:
    inputs:
      JM_ALBUM_ID:
        type: string
        description: 本子id（多个id用-隔开，如 '123-456-789'）
        required: true

      JM_PHOTO_ID:
        type: string
        description: 章节id（单独下载章节，多个id同上）
        required: true

jobs:
  crawler:
    runs-on: ubuntu-latest
    env:
      # 工作流输入
      JM_ALBUM_ID: ${{ github.event.inputs.JM_ALBUM_ID }}
      JM_PHOTO_ID: ${{ github.event.inputs.JM_PHOTO_ID }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: 安装jmcomic（pip）
        if: ${{ github.ref != 'refs/heads/dev' }}
        run: |
          pip install jmcomic -i https://pypi.org/project --upgrade

      - name: 运行下载脚本
        run: jmcomic ${{ env.JM_ALBUM_ID }} p${{ env.JM_PHOTO_ID }} --option="./option.yml"

      - name: 上传结果
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.JM_ALBUM_ID }}.zip
          path: ./result/pdf
          if-no-files-found: error
          retention-days: 90

      - name: 开启 SSH 服务 (Start SSH service)
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15