name: 下载JM本子 (dispatch)

on:
  workflow_dispatch:
    inputs:
      JM_ALBUM_ID:
        type: string
        description: 本子id（多个id用-隔开，如 '123-456-789'）
        required: true

      JM_PHOTO_ID:
        type: string
        description: 章节id（单独下载章节，多个id同上）
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      # 工作流输入
      JM_ALBUM_ID: ${{ github.event.inputs.JM_ALBUM_ID }}
      JM_PHOTO_ID: ${{ github.event.inputs.JM_PHOTO_ID }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependency
        run: |
          pip install -r requirements-dev.txt

      - name: 安装jmcomic（pip）
        run: |
          pip install jmcomic -i https://pypi.org/project --upgrade

      - name: 运行下载脚本
        run: jmcomic ${{ env.JM_ALBUM_ID }} p${{ env.JM_PHOTO_ID }} --option="./option.yml"

      - name: 下载 gs
        run: |
          sudo apt update
          sudo apt install ghostscript

      - name: 压缩 pdf
        run: |
          mkdir -p ./resources
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile="./result/pdf/${JM_ALBUM_ID}_compressed.pdf" "./result/pdf/${JM_ALBUM_ID}.pdf"
          cp "./result/pdf/${JM_ALBUM_ID}_compressed.pdf" "./resources/${JM_ALBUM_ID}.pdf"

      - name: 上传到 Github，这里要用 Github Actions Bot 的信息
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "update"
          git push

      - name: 开启 SSH 服务 (Start SSH service)
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15